version: "2"
services:
  app:
    container_name: myapp_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - VIRTUAL_HOST=52.77.223.186
      - VIRTUAL_PORT=27017




  #  links:
  #    - mongo
  #mongo:
  #  container_name: mongo
  #  image: mongo
  #  volumes:
  #    - ./data:/data/db
  #  ports:
  #    - "27017:27017"

